# Site settings
title:  windha
email: windha@gmail.com
description: >
  A  developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://windha.com" # the base hostname & protocol for your site
twitter_username: windha
github_username:  windha

# Build settings
markdown: kramdown
